name: AutoDailyRss

on:
  schedule:
  - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        
    - name: Run Script
      run: |
        python ncm_artists_rss/main.py -t ${{ secrets.TOKEN }} -c ${{ secrets.CHAT_ID }}
        python dlsite_maniax_rss/main.py -t ${{ secrets.TOKEN }} -c ${{ secrets.CHAT_ID }}
