name: AutoDailyRss

on:
  schedule:
  - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: Install Requirements
      run: |
        pip3 install setuptools
        pip3 install -r requirements.txt
        
    - name: Run Script
      run: |
        python3 ncm_artists_rss/main.py -t ${{ secrets.TOKEN }} -c ${{ secrets.CHAT_ID }}
        python3 dlsite_maniax_rss/main.py -t ${{ secrets.TOKEN }} -c ${{ secrets.CHAT_ID }}
